version: "3.4"

services:
    tic-tac-toe-backend:
        build: .
        container_name: tic-tac-toe-backend
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - tic-tac-toe-network

    nginx:
        image: nginx:alpine
        container_name: tic-tac-toe-nginx
        depends_on:
            - tic-tac-toe-backend
        ports:
            - "8020:8020"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - tic-tac-toe-network

networks:
    tic-tac-toe-network:
